### ISSUE TITLE
Link does not working

### ISSUE THREAD

**Issue by 5KS** [kdreally/willso.me#1]
https://github.com/kdreally/willso.me/blob/7eb09178f98151879a64c0dd7cca592b93ebb976/f/blog.html#L77

Hello.

Try change 'href' from
contracruise.com ->
http://contracruise.com

Else it tries to open:
https://willso.me/f/contracruise.com
which is "Not Found: 404".  BTW, cruise is cancelled i think.

PS: http://contracruise.com opens for me, and redirects to https.  https://contracruise.com times-out.

**Comment by NoSJW** [comment]
I realized that, but the link itself ruined the hidden-ness of the text, and instead of messing with CSS I decided to do away with it for now.

**Comment by 5KS** [comment]
text&lt;a&gt;*&lt;/a&gt;?
